### ISSUE TITLE
I think, The sqlite structure of Bear has changed.

### ISSUE THREAD

**Issue by junorouse** [redspider/pybear#2]
```
Traceback (most recent call last):
  File "post.py", line 17, in <module>
    tag = b.tag_by_title('blog', 'desc')
  File "/Users/pace/junoim/1Dev/projects/bear-blog/bear.py", line 154, in tag_by_title
    cursor.execute("SELECT * FROM ZSFNOTETAG WHERE ZTITLE=?", [title])
sqlite3.OperationalError: no such table: ZSFNOTETAG
```

**Comment by junorouse** [comment]
the file moved to this one.

sqlite_url = "~/Library/Containers/net.shinyfrog.bear/Data/Documents/Application Data/database.sqlite"

**Comment by rootkovska** [comment]
This has been fixed here: https://github.com/redspider/pybear/commit/0bd8e90eb603d771588eb9d0925d9043a11875ab
